### ISSUE TITLE
Crash after adding ExtendedAutomation

### ISSUE THREAD

**Issue by AnonymousPuppy** [Arkandos/ExtendedAutomation#1]
Using a custom modpack, forge .1240, and ExtendedAutomation and Braincore version 0.3. After adding ExtendedAutomation and Braincore, I'm getting a startup crash. It seems to be related to Mariculture.

Crash report: http://pastebin.com/9Q5pS47q

Please fix this ASAP, thank you :)

**Comment by Arkandos** [comment]
Could I please get your mariculture version?

**Comment by AnonymousPuppy** [comment]
Mariculture-Base-1.7.10-1.2.4-163.jar

It's the latest from Jenkins. If you need any other mod version, just do CTRL+F on the crashlog and search for the mods name. It should show the version as well :)

**Comment by Arkandos** [comment]
Could you try and see if it works using the last recommended version?
1.2.3d

Also, isn't the Mariculture jenkins down or can I just no access it?

**Comment by AnonymousPuppy** [comment]
Yeah it appears to be down at the moment. Sadly I can't use the last recommended version, because it crashes with other mods. It's over 4 months old, and incompatibilities are prevalent.

**Comment by Arkandos** [comment]
Just out of curiosity, what mods does it crash with?

And sadly, I cannot provide compatibility with a version I cannot access. So this is closed until the jenkins opens again

**Comment by AnonymousPuppy** [comment]
It crashes with hunger overhaul and one other mod I believe. I can give you a link to a dropbox folder with the Mariculture version that I am running, but I don't know if that is allowed or not.
