### ISSUE TITLE
This mod broke with the new mekanism 8 mod

### ISSUE THREAD

**Issue by crunkazcanbe** [Arkandos/ExtendedAutomation#2]
http://pastebin.com/FVd7tmk7 as the title says. 

Thanks!

-Crunk

**Comment by Arkandos** [comment]
I'll try to get a new version out with Mekanism 8 support

**Comment by crunkazcanbe** [comment]
Thank you !

-Crunk

**Comment by Arkandos** [comment]
I dont have any possibilities to test this anytime soon, but try this:
https://dl.dropboxusercontent.com/u/37675952/BrainCore-1.7.10-0.3.3.jar

Please tell me if it works for you.

**Comment by crunkazcanbe** [comment]
Ok man as soon as i get off work. Thank you!

**Comment by crunkazcanbe** [comment]
Man I want to thank you a lot for this. :) It works 100% . I appreciate it.

-Crunk

**Comment by Arkandos** [comment]
Just checking, do the crusher recipes still work? Like pams plants to biofuel etc?

**Comment by accessdenied0** [comment]
Dear @Arkandos ,

Maybe I can be here of assistance. So far I can see, the recipes in the crusher do not work for (pam's) harvestcraft seemingly.

access_denied

**Comment by Arkandos** [comment]
@accessdenied0 are you using Braincore 0.3.3?

**Comment by accessdenied0** [comment]
Hello @Arkandos ,

Yes, otherwise it would crash. I took the version from the dropbox-link which are listed here.

access_denied

**Comment by Arkandos** [comment]
@accessdenied0  I can't test it myself right now, but try and see if this one works 
https://dl.dropboxusercontent.com/u/37675952/BrainCore-1.7.10-0.3.4.jar

**Comment by accessdenied0** [comment]
Dear @Arkandos ,

Thank you for this extremely fast response. It fixed it partly (if it is supposed to crush only the fruits and vegetables, otherwise it is fully fixed) The seeds from harvestcraft aren't loaded (unlike the vanilla ones)... But it works very well.

thank you very much,

access_denied

**Comment by Arkandos** [comment]
Don't think I ever coded in the seeds. Might consider that.
